name: Generate ZIP for Release

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
          attestations: write
          contents: write
          id-token: write

        timeout-minutes: 70

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Build PHP
              run: composer install --no-dev --optimize-autoloader

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install Packages w/ Bun
              run: bun install

            - name: Build with Bun
              run: bun run build

            - name: Create Release ZIP
              uses: thedoctor0/zip-release@master
              with:
                  type: 'zip'
                  filename: 'frames-integration-for-farcaster.zip'
                  exclusions: '/*node_modules/* readme.md package.json .gitignore .eslintrc.js .nvmrc .stylelintrc.json phpcs.xml tsconfig.json bun.lockb .vscode/ .vscode/* .wordpress-org/ .wordpress-org/* src/ src/* src/components/ src/components/* src/hooks/ src/hooks/* src/utils/ src/utils/* /*.git/* /*.github/*'

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: frames-integration-for-farcaster
                  path: frames-integration-for-farcaster.zip

            - name: Upload to Release
              run: gh release upload ${{ github.event.release.tag_name }} frames-integration-for-farcaster.zip
              env:
                GITHUB_TOKEN: ${{ github.TOKEN }}

            - name: Unzip Folder for WP.org
              uses: montudor/action-zip@v1
              with:
                  args: unzip -qq frames-integration-for-farcaster.zip -d frames-integration-for-farcaster

            - name: Upload Plugin to WP.org
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@2.1.0
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SLUG: frames-integration-for-farcaster
                  BUILD_DIR: ./frames-integration-for-farcaster

            - name: Attest Build Provenance
              uses: johnbillion/action-wordpress-plugin-attestation@0.5.1
              with:
                zip-path: ${{ steps.deploy.outputs.zip-path }}